### ISSUE TITLE
Daybloom uncraftable

### ISSUE THREAD

**Issue by TheIcyOne** [TheIcyOne/Easy-Pickings#1]
No recipe currently exists to produce a daybloom. Suggest shapeless 2 yellow flowers and a red dye, and maybe some seeds.

**Comment by JohnMillerBRZ** [comment]
Add clay as a binder.

**Comment by SjetCraft** [comment]
Add clay as a binder.

**Comment by TheIcyOne** [comment]
In hindsight I think this mod works better without recipes, none of the tools are designed to be used as-is by the end user, except maybe the fires, and they are better left to server admins anyway. Let the pack devs tweak as they wish without conflicting with an expected recipe.
