### ISSUE TITLE
[Bug] Daybloom and Nightshade have place/break sounds of stone, are rendered as blocks in hand rather than tiles

### ISSUE THREAD

**Issue by Luke616** [TheIcyOne/Easy-Pickings#2]
Title, both flowers have stone placing/breaking sounds rather than foliage. The flowers are also rendered like a block when they are in your hand, rather than as a flat tile like the other flowers in botania.

Thanks!
Luke616

**Comment by TheIcyOne** [comment]
The hand renders are intended, I personally prefer the 3D render style. The stone place/break issues are a bug, though.
