### ISSUE TITLE
cant view any recipes and unstable goo has no tool tip caused by JEI.

### ISSUE THREAD

**Issue by Zer0Lyfe** [TheIcyOne/Easy-Pickings#3]
it gives an error with all the items and the tool tip for the unstable goo is giving an error

https://pastebin.com/tRkXGbdr
![2017-11-20_11 01 26](https://user-images.githubusercontent.com/28994351/33000340-5a30393e-cde2-11e7-8e7e-6c0e983dc5db.png)

**Comment by TheIcyOne** [comment]
The error message could be handy, as well as the log, since this does not happen with forge alone.

**Comment by Zer0Lyfe** [comment]
https://pastebin.com/9RHy4P7M
It happens with JEI by itself.

Mods list:
mcp - Minecraft Coder Pack - 9.42
FML - Forge Mod Loader - 8.0.99.99
forge - Minecraft Forge - 14.23.0.2550
jei - Just Enough Items - 4.8.1.120
easypickings - Easy Pickings - 1.2.0

**Comment by TheIcyOne** [comment]
Turns out I forgot about this, will be fixed in next update, sorry >.>
