### ISSUE TITLE
[Enhancement/Suggestion/I'm Greedy] Maybe Jei support for infused fire conversions?

### ISSUE THREAD

**Issue by TeetoKaziim** [TheIcyOne/Easy-Pickings#4]
You can just close this and tell me to shut up, of course. But It'd be kinda neat.

It's not like I'm planning on using it as a serious crafting mechanic in a pack or anything. That'd be ridiculous ha ha ha ; _ ; 

Seriously thank you for the fire (AND especially the CONFIG oh my GOSH) anyway. It's rad and neato.

**Comment by TheIcyOne** [comment]
That's actually a pretty good idea. I'll have a peek into the feasibility of doing this, because I would prefer not to have to do the conversions properly ;)

*it actually only exists because I plan to use it as a serious crafting mechanic*

**Comment by TheIcyOne** [comment]
i gotchu fam
