### ISSUE TITLE
Unstable Goo tooltips aren't localized

### ISSUE THREAD

**Issue by DaedalusGame** [TheIcyOne/Easy-Pickings#5]
try number two because apparently i'm repobanned :^)

it would be good for translation efforts and packmaking to have the ability to configure these strings in the lang files, currently they're static strings.

**Comment by TheIcyOne** [comment]
Did I not do that already?

**Comment by TheIcyOne** [comment]
I did not. Hang on, I'll dump the new build on CF in a bit.

**Comment by TheIcyOne** [comment]
It'll probably take a while to be approved, CF staff normally leave around now.
