### ISSUE TITLE
The two passive flowers don't do anything?

### ISSUE THREAD

**Issue by Darkmega18** [TheIcyOne/Easy-Pickings#8]
The main page said they'd generate mana like they used to, but they're not doing anything it seems as far as sending to spreaders to be fired off or sparkling as they generate. Not that it's a massive issue, since there's other ways to mana, but thought that was kinda a selling point of the mod. :V

**Comment by TheIcyOne** [comment]
They do generate mana, it's just incredibly slow by default. I'll probably make it configurable in my next update.

**Comment by Darkmega18** [comment]
they don't sparkle and I couldn't attach them to the spread using a wand. so I had doubts. :V

**Comment by TheIcyOne** [comment]
Yeah, because of the way I had to implement them to make them useable without botania they can't be attached with the wand, they just provide mana to nearby mana accepting blocks. I can make them sparkle if that helps.

**Comment by Darkmega18** [comment]
while they have mana, but yeah, that'd be nice. just for some immediate feedback that they're actually working like botania does.
